# Generated by Django 4.0.5 on 2022-06-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='answers',
        ),
        migrations.AddField(
            model_name='ticket',
            name='answers',
            field=models.ManyToManyField(to='supportapp.messages', verbose_name='Ответы'),
        ),
    ]
